name: audio_classification
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - pyaudio
  - librosa
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - numpy
  - matplotlib
  - cudatoolkit=11.3  # Optional if you want GPU support; can remove or adjust as needed
